# Generated by Django 2.1.7 on 2020-07-06 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signupuser',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=50)),
                ('mob', models.CharField(max_length=15, unique=True)),
                ('city', models.CharField(default='', max_length=50)),
                ('job', models.CharField(default='', max_length=300)),
                ('password', models.CharField(default='', max_length=15)),
                ('cpassword', models.CharField(default='', max_length=15)),
            ],
        ),
    ]
