# Generated by Django 2.1.7 on 2020-07-07 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_signupuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signupuser',
            name='job',
        ),
    ]
