# Generated by Django 2.1.7 on 2020-07-07 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_remove_signupuser_job'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Signupuser',
        ),
    ]
